version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: new_db_homes
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: new_db_homes
    ports:
      - "5432:5432"
    volumes:
      - new_db_data:/var/lib/postgresql/data


volumes:
  new_db_data:
